title: nextjs-application-template
description: A template for quickly starting Next.js application development
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
